### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by fazliddin** [noumo/easyii-shop#2]
I am following doc: http://easyiicms.com/docs/install.

Archive method results blank page

Composer method say that there is no stable version

**Comment by fazliddin** [comment]
OK, I figured out that CMS does not work under domain's subfolder.
There is also bug in 76 line of web.php. It must be:
return array_merge_recursive($config, require($webroot . '/vendor/noumo/easyii/config/easyii.php'));

**Comment by noumo** [comment]
thanks, fixed
