### ISSUE TITLE
Redactor language config error in lang zh-CN

### ISSUE THREAD

**Issue by robinclark007** [noumo/easyii-shop#5]
if I change language settings in the easyii.php 
`
'language' => 'zh-CN',
`

the redactor will try to locate the zh.js according to the 

`
Data::getLocale();  //return zh ,this make no sense in substr(Yii::$app->language, 0, 2)
`
because the translation file named zh_cn.js so it won't find the right js file.
so I recommend change the code in the get locale function in the 
helpers/Data

```
    public static function getLocale()
    {
        //fix inconsistence between En and Cn translation
        if(Yii::$app->language === 'zh-CN'){
          return 'zh_cn';
        }
        return strtolower(substr(Yii::$app->language, 0, 2));
    }
```

**Comment by noumo** [comment]
fixed in dev branch
